// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5dDIev7H5eXuAhLZ4pbPWOV8MUGJ8_mg',
    appId: '1:44329246590:web:34e30eb0dd8f0bd7255d2f',
    messagingSenderId: '44329246590',
    projectId: 'cotani-gdsc',
    authDomain: 'cotani-gdsc.firebaseapp.com',
    storageBucket: 'cotani-gdsc.appspot.com',
    measurementId: 'G-SRC805G6LQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCbu0AtAY2of-1ahnoGLTLaedwbUg8RuM',
    appId: '1:44329246590:android:548cae52fbee58ea255d2f',
    messagingSenderId: '44329246590',
    projectId: 'cotani-gdsc',
    storageBucket: 'cotani-gdsc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzBeUaj8QW70FzIDkP-v-r81hha7nX2oU',
    appId: '1:44329246590:ios:1697181ef9bf7eaf255d2f',
    messagingSenderId: '44329246590',
    projectId: 'cotani-gdsc',
    storageBucket: 'cotani-gdsc.appspot.com',
    iosBundleId: 'com.example.cotaniNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzBeUaj8QW70FzIDkP-v-r81hha7nX2oU',
    appId: '1:44329246590:ios:34d4cde1229375f8255d2f',
    messagingSenderId: '44329246590',
    projectId: 'cotani-gdsc',
    storageBucket: 'cotani-gdsc.appspot.com',
    iosBundleId: 'com.example.cotaniNew.RunnerTests',
  );
}
